//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConexionAvance : DbContext
    {
        public ConexionAvance()
            : base("name=ConexionAvance")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Metrado> Metrado { get; set; }
        public virtual DbSet<Metrado_Tmp> Metrado_Tmp { get; set; }
        public virtual DbSet<MetradoAvance> MetradoAvance { get; set; }
        public virtual DbSet<MetradoAvanceHito> MetradoAvanceHito { get; set; }
        public virtual DbSet<MetradoCampo> MetradoCampo { get; set; }
        public virtual DbSet<MetradoCampo_Tmp> MetradoCampo_Tmp { get; set; }
        public virtual DbSet<MetradoHito> MetradoHito { get; set; }
    }
}
