//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDMarinaConexion : DbContext
    {
        public BDMarinaConexion()
            : base("name=BDMarinaConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CondicionPapeleta> CondicionPapeletas { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<GradoPersonal> GradoPersonals { get; set; }
        public virtual DbSet<PapeletaMultiple> PapeletaMultiples { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<TipoPaleleta> TipoPaleletas { get; set; }
    }
}
