//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDMarinaConexion : DbContext
    {
        public BDMarinaConexion()
            : base("name=BDMarinaConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calendario> Calendario { get; set; }
        public virtual DbSet<CondicionPapeleta> CondicionPapeleta { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Dependencia> Dependencia { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<FrecuenciaGuardia> FrecuenciaGuardia { get; set; }
        public virtual DbSet<GradoPersonal> GradoPersonal { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Restricciones> Restricciones { get; set; }
        public virtual DbSet<RolGuardia> RolGuardia { get; set; }
        public virtual DbSet<Sueldo> Sueldo { get; set; }
        public virtual DbSet<TipoGuardia> TipoGuardia { get; set; }
        public virtual DbSet<TipoPaleleta> TipoPaleleta { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<Vacaciones> Vacaciones { get; set; }
        public virtual DbSet<PapeletaMultiple> PapeletaMultiple { get; set; }
    }
}
