//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrecuenciaGuardia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FrecuenciaGuardia()
        {
            this.RolGuardia = new HashSet<RolGuardia>();
        }
    
        public int IdFrecuencia { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public string Etiqueta { get; set; }
        public Nullable<System.TimeSpan> HoraInio { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
        public Nullable<int> TotalHoras { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolGuardia> RolGuardia { get; set; }
    }
}
