//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetradoAvanceHito
    {
        public long IdMetradoHito { get; set; }
        public long IdMetradoAvance { get; set; }
        public decimal PorcentajeAvanceReal { get; set; }
        public decimal MetradoAvanceReal { get; set; }
        public string IdUsuarioRegistro { get; set; }
        public string IdUsuarioModifico { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModifico { get; set; }
    
        public virtual MetradoAvance MetradoAvance { get; set; }
        public virtual MetradoHito MetradoHito { get; set; }
    }
}
