//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PapeletaMultiple
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PapeletaMultiple()
        {
            this.CondicionPapeletas = new HashSet<CondicionPapeleta>();
        }
    
        public int IdPapeleta { get; set; }
        public string NumeroPapeleta { get; set; }
        public Nullable<int> IdPersonalRegistro { get; set; }
        public Nullable<int> IdPersonalEnturno { get; set; }
        public Nullable<int> IdPersonalRemplazo { get; set; }
        public Nullable<int> IdTipoPapeleta { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaCubrir { get; set; }
        public Nullable<System.DateTime> FechaDevolverTurno { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public string UsuarioModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionPapeleta> CondicionPapeletas { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Personal Personal1 { get; set; }
        public virtual TipoPaleleta TipoPaleleta { get; set; }
    }
}
