//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.CondicionPapeleta = new HashSet<CondicionPapeleta>();
            this.RolGuardia = new HashSet<RolGuardia>();
            this.PapeletaMultiple = new HashSet<PapeletaMultiple>();
            this.PapeletaMultiple1 = new HashSet<PapeletaMultiple>();
        }
    
        public int IdPersonal { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdGrado { get; set; }
        public Nullable<int> IdDependencia { get; set; }
        public Nullable<int> CodigoSenal { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Cip { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public string NDocumento { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Correo { get; set; }
        public string Sexo { get; set; }
        public byte[] Foto { get; set; }
        public string Dirección { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public string UsuarioActualizacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionPapeleta> CondicionPapeleta { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Dependencia Dependencia { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual GradoPersonal GradoPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolGuardia> RolGuardia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapeletaMultiple> PapeletaMultiple { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PapeletaMultiple> PapeletaMultiple1 { get; set; }
    }
}
