//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolGuardia.Datos.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolGuardia
    {
        public int IdRolGuardia { get; set; }
        public int IdTipoGuardia { get; set; }
        public int IdCalendario { get; set; }
        public int IdPersonal { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public Nullable<int> IdFrecuencia { get; set; }
        public Nullable<int> IdPersonalCambio { get; set; }
        public Nullable<System.DateTime> FechaProgramada { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Observacion { get; set; }
        public string UsuarioRegistro { get; set; }
        public string UsuarioModificacioon { get; set; }
        public string Estado { get; set; }
    
        public virtual Calendario Calendario { get; set; }
        public virtual FrecuenciaGuardia FrecuenciaGuardia { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TipoGuardia TipoGuardia { get; set; }
    }
}
